services:
  mysql:
    image: mysql:8
    container_name: mysql-8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./internal/infra/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.12.14-management
    container_name: rabbitmq-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - .docker/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker/rabbitmq/log/:/var/log/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-app
    restart: always
    ports:
      - 8080:8080
      - 50051:50051
      - 8081:8081
    environment:
      DB_DRIVER: "mysql"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_NAME: "orders"
      WEB_SERVER_PORT: ":8080"
      GRPC_SERVER_PORT: "50051"
      GRAPHQL_SERVER_PORT: "8081"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      RABBITMQ_PORT: "5672"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy